project:
  type: book
  output-dir: docs

book:
  favicon: img/logo.png
  twitter-card: true
  site-url: https://stringhinilab.github.io/GitHubProceduresLab/
  repo-url: https://github.com/StringhiniLab/GitHubProceduresLab
  repo-actions: [edit, issue]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  title: "GitHub Lab Procedures"
  subtitle: "A repository management start kit for new lab members"
  author: "Florencia D'Andrea"
  date: "11/29/2024"
  chapters:
    - index.qmd
    - lab-design.qmd
    - roles.qmd
    - onboarding.qmd
    - start-project.qmd
    - dailytasks.qmd
    - offboarding.qmd
  sidebar:
    title: |
      Dr. Stringhini's Lab
      School of Population and Public Health
      University of British Columbia
    search: true
    logo: img/logo.png

bibliography: references.bib
bibliographystyle: apa

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt






