project:
  type: book
  output-dir: docs

book:
  title: "GitHub Lab Procedures"
  subtitle: "Stringhini's Lab - University of British Columbia"
  author: "Florencia D'Andrea"
  date: "11/29/2024"
  chapters:
    - index.qmd
    - mantainer.qmd
    - onboarding.qmd
    - start-project.qmd
    - dailytasks.qmd
    - offboarding.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt





