project:
  type: book
  output-dir: docs

book:
  title: "GitHub Lab Procedures"
  subtitle: "A quick guide to effective repository management for research purposes"
  author: "Florencia D'Andrea"
  date: "11/29/2024"
  chapters:
    - index.qmd
    - mantainer.qmd
    - onboarding.qmd
    - start-project.qmd
    - dailytasks.qmd
    - offboarding.qmd
  sidebar:
    title: |
      Dr. Stringhini's Lab
      School of Population and Public Health
      University of British Columbia
    search: true
    logo: img/logo.png

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt





