project:
  type: book
  output-dir: docs

book:
  favicon: img/logo.png
  twitter-card: true
  site-url: https://stringhinilab.github.io/GitHubProceduresLab/
  repo-url: https://github.com/StringhiniLab/GitHubProceduresLab
  repo-actions: [edit, issue]
  downloads: [pdf, epub]
  title: "Code Management Guidelines"
  subtitle: "R and GitHub Starter Kit for New Team Members"
  author: "Florencia D'Andrea"
  date: "11/29/2024"
  chapters:
    - part: index.qmd
      chapters:
      - lab-design.qmd
      - roles.qmd
    - part: "Practical Steps"
      chapters:
      - onboarding.qmd
      - start-project.qmd
      - dailytasks.qmd
      - offboarding.qmd
  sidebar:
    title: |
      Dr. Stringhini's Lab
      School of Population and Public Health
      University of British Columbia
    search: true
    logo: img/logo.png

bibliography: references.bibtex

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt






