# Roles {.unnumbered}

## GitHub Organization Manager

The Owner of the organization can add new members. Ensure that new lab members join the GitHub Organization. Follow the instructions on how to do it in [Inviting users to join your organization](https://docs.github.com/en/organizations/managing-membership-in-your-organization/inviting-users-to-join-your-organization). 

::: {.callout-warning appearance="simple"}
You will need to wait for the new member to create a GitHub account before you can add them. They should share their username with you.
:::

### Responsibilities 🎯
- Add new lab members to the GitHub Organization.

## GitHub Team Maintainer 

At least one person in the lab will be assigned as the Team Maintainer of the GitHub organization. This role will allow them to add and remove members from the team, granting or revoking access to private repositories.

For this, it’s important to assign the Lab Member in charge the **Team Maintainer** role for the Lab Team.  
Follow the instructions in [Assigning the team maintainer role to a team member](https://docs.github.com/en/organizations/organizing-members-into-teams/assigning-the-team-maintainer-role-to-a-team-member#about-team-maintainers) 

If properly assigned the label `mantainer` should appear next to they name in this repository: [https://github.com/orgs/StringhiniLab/teams/lab-team](https://github.com/orgs/StringhiniLab/teams/lab-team).

### Responsibilities 🎯
- Add new lab members to the Lab Team.
- Remove team members who are no longer part of the lab.
- Assign other members as Team Maintainers if necessary.

